sudo: false
dist: trusty
language: php
php:
  - "7.1"
  - "7.0"
  - "5.6"
  - "5.5"
  # hhvm-3.26 changed its PHP_VERSION to be 7.1.99 instead of 5.6.99
  # which breaks 'composer install' because HHVM does not support
  # use of empty property keys, whereas PHP 7
  # https://github.com/composer/composer/issues/7361
  - "hhvm-3.24"
  - "hhvm-3.21"
  - "hhvm-3.18"
install:
  - composer install
script:
  - composer test
after_success:
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.2/coveralls.phar
  - chmod +x coveralls.phar
  - ./coveralls.phar -v
notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-dev"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} %{author}): %{message} - %{build_url}"
